DROP TABLE IF EXISTS memory_bank;

CREATE TABLE memory_bank (
    row_id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    user_id TEXT NOT NULL,
    num1 INTEGER NOT NULL,
    operator TEXT NOT NULL,
    num2 INTEGER NOT NULL,
    ans INTEGER NOT NULL
);